name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Dockerfile syntax
        run: |
          docker run --rm -i hadolint/hadolint hadolint --no-fail - < Dockerfile

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU (for cross-platform)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build camelot-builder:latest
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: camelot-builder:latest, ghcr.io/${{ github.repository_owner }}/camelot-builder:latest

  build-sdk:
    name: Build camelot-builder-sdk image
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU (for cross-platform)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate camelot-builder-sdk image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.sdk
        target: validation
        push: false

    - name: Build camelot-builder-sdk:latest
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.sdk
        target: final
        push: false
        tags: camelot-builder-sdk:latest, ghcr.io/${{ github.repository_owner }}/camelot-builder-sdk:latest
